Add issue templates
southworks/amazon-lex-happybirthday-bamboohr-slack-bot pull request #12
Opened 2020-08-20 15:37 UTC by ffarguelles

### Description
This PR adds the templates to be used when someones creates an issue on the project.

### Changes Made

- Added `.github/` folder to main directory
- Added `bug_report.md` template
- Added `feature_request.md` template

2020-08-20 16:01 UTC, totigm approved these changes

2020-08-20 16:39 UTC, rod6214 requested changes
Check if Type: syntax set automatically the label before create the issue, otherwise put Type: doesn't make sense

2020-08-20 20:47 UTC, rod6214 approved these changes

2020-08-25 14:04 UTC, nahuelschlegel approved these changes

2020-08-25 14:06 UTC, merged