Added pull request template
southworks/amazon-lex-happybirthday-bamboohr-slack-bot pull request #13
Opened 2020-08-20 16:06 UTC by rod6214

## Description
This PR adds the templates to be used when someones creates a pull request on the project.

## Specific Changes
- Added `.github/` folder
- Added `PULL_REQUEST_TEMPLATE.md` template

2020-08-20 16:19 UTC, totigm requested changes
Descriptions shouldn't be commented, so the user can see them when he opens the markdown editor.
I'm not very familiar with GitHub templates, but I think you should add something like what @Farguelles did on PR #12, I'll leave you a screenshot and the [link](https://github.com/southworks/amazon-lex-happybirthday-bamboohr-slack-bot/pull/12/files#diff-74c2649c999338ed7a2833d79d4b25c3R1-R7) to that lines:
![image](https://user-images.githubusercontent.com/64804554/90797769-749d2580-e2e7-11ea-8444-331fd5b7b7d6.png)

2020-08-25 18:18 UTC, nahuelschlegel approved these changes

2020-08-25 18:21 UTC, ghost approved these changes

2020-08-25 18:52 UTC, facumartin-zz approved these changes

2020-08-25 19:23 UTC, nahuelschlegel approved these changes

2020-08-25 19:26 UTC, ffarguelles approved these changes

2020-08-25 19:56 UTC, totigm approved these changes

2020-08-25 19:57 UTC, merged