Improve repo structure
southworks/amazon-lex-happybirthday-bamboohr-slack-bot pull request #17
Opened 2020-08-25 15:25 UTC by ffarguelles

## Description
This PR updates project structure according to what we talk with BTK team

## Changes made
- Create `docs/` folder and `images/` subfolder
- Update png path in main readme
- Move `serverless.md` to `docs/`
- Reference docs in `birthday-bot/` readme

2020-08-26 13:22 UTC, totigm reviewed
We should add a docs/README.md with a table of contents (right now it'd only point to serverless, but it will be useful when we add more documentation).
The birthday-bot/README.md should have the bot's description, the root README would fit well there. In the root README we should just give a brief description and link to other markdown files.

2020-08-27 20:58 UTC, rod6214 requested changes

2020-08-28 13:29 UTC, totigm approved these changes
Nice @Farguelles! Thanks for considering my suggestions!

2020-08-28 13:54 UTC, ghost approved these changes

2020-08-28 14:02 UTC, rod6214 approved these changes

2020-08-28 14:03 UTC, Bill7zz approved these changes
Approved

2020-08-28 14:09 UTC, merged